# Generated by Django 4.0.5 on 2022-07-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_base_magasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_magasin_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('photo_1', models.TextField(verbose_name='Фото 1')),
                ('photo_2', models.TextField(blank=True, verbose_name='Фото 2')),
                ('photo_3', models.TextField(blank=True, verbose_name='Фото 3')),
                ('photo_4', models.TextField(blank=True, verbose_name='Фото 4')),
                ('photo_5', models.TextField(blank=True, verbose_name='Фото 5')),
                ('photo_6', models.TextField(blank=True, verbose_name='Фото 6')),
                ('photo_7', models.TextField(blank=True, verbose_name='Фото 7')),
                ('photo_8', models.TextField(blank=True, verbose_name='Фото 8')),
                ('about', models.TextField(verbose_name='О товаре')),
                ('price', models.CharField(blank=True, max_length=20, verbose_name='Цена')),
                ('tema', models.CharField(max_length=20, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_img', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
